spring:
  application:
    name: client-service
  redis:
    host: localhost
    port: 6379

url:
  subscriber-service: http://localhost:8084

server:
  port: 8082

logging:
  level:
    org.springframework.data.redis: DEBUG
